name: 📜 Protocol Release
permissions:
  "contents": "write"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        type: string
      description:
        description: 'Description Text'
        required: false
        type: string
        default: ""

jobs:
  generate-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install flatc
        uses: Nugine/setup-flatc@v1
        with:
          version: "24.3.25"

      - name: Generate Java code from FlatBuffers
        run: |
          mkdir -p generated/java
          flatc --java -o generated/java schemas/*.fbs

      - name: Generate Rust code from FlatBuffers
        run: |
          mkdir -p generated/rust
          flatc --rust -o generated/rust schemas/*.fbs

      - name: Generate Rust code from FlatBuffers
        run: |
          mkdir -p generated/rust
          flatc --rust -o generated/rust schemas/*.fbs

      - name: Create Cargo.toml for Rust Code
        run: |
          cat <<EOL > generated/rust/Cargo.toml
          [package]
          name = "generated"
          version = "${{ github.event.inputs.version }}"
          edition = "2021"

          [dependencies]
          flatbuffers = "25.2.10"

          [build-dependencies]
          flatbuffers = "25.2.10"
          EOL

      - name: Commit generated code
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add generated/
          git commit -m "Update generated code ${GITHUB_EVENT_INPUTS_VERSION}"

      - name: Push generated code to branch
        run: |
          git push origin HEAD:refs/heads/generated --force
